### ISSUE TITLE
Appcelerator Platform Compatibility

### ISSUE THREAD

**Issue by Sophrinix** [CodexLabs/TiCalabash#1]
This plugin was originally designed to work for Titanium OSS. 
Given that Many Titanium OSS developers are also Appcelerator Platform developers as well, we need to support both CLI.

**Comment by jasonchongbinary** [comment]
Is there any workaround to make this work on Appcelerator Platform?

**Comment by Sophrinix** [comment]
the ugly work around is to build your titanium project and then go to the build directory and run calabash on the project directly. I will finally have some time this week to work on a real fix for this issue.

**Comment by jasonchongbinary** [comment]
I've tried to run the project from the build directory before. Unfortunately the app is not able to find the assets (Like images) in the app. That's why i still couldn't test it properly.

**Comment by Sophrinix** [comment]
This almost works now. It does register as a command again. I am now thinking of the best way to handle this ruby issue:
`Unable to activate run_loop-2.2.0, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in `activate'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1428:in `each'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1428:in `activate_dependencies'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1410:in `activate'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems.rb:220:in `rescue in try_activate'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems.rb:213:in `try_activate'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/Users/andrewmcelroy/Desktop/alloy_fugitive/build/iphone/features/ios/support/env.rb:1:in `<top (required)>'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/bin/cucumber:23:in `load'
/Users/andrewmcelroy/.rbenv/versions/2.2.3/bin/cucumber:23:in `<main>'`

**Comment by sachin123sharma** [comment]
I am also facing same issue. After Running or Executing  ti calabash command for iOs Project , I am Using Titanium SDK 5.4.0GA , Xcode 7.3.1
Unable to activate run_loop-2.2.0, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2284:in `raise_if_conflicts'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1407:in`activate'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in`each'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1409:in`activate'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems.rb:193:in`try_activate'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
/Users/ssharma/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in`require'
/Users/ssharma/Documents/Appcelerator_Studio_Workspace/FieldResidential_Mocha/build/iphone/features/ios/support/env.rb:1:in `<top (required)>'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in`load'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in`load_file'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in`each'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in`load_step_definitions'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in`execute!'
/Users/ssharma/.rvm/gems/ruby-2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/ssharma/.rvm/gems/ruby-2.3.0/bin/cucumber:23:in`load'
/Users/ssharma/.rvm/gems/ruby-2.3.0/bin/cucumber:23:in `<main>'
/Users/ssharma/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`eval'
/Users/ssharma/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Please provide your input.
