### ISSUE TITLE
App does not exist at path or is not an app bundle.

### ISSUE THREAD

**Issue by AndreaVitale** [CodexLabs/TiCalabash#3]
I created a sample titanium app and I was trying to make some simply test as you specified [here](https://github.com/CodexCasts/episode-21-ticalabash-getting-started).

I was unable to get it working cause I always got this error:

```
building the -cal scheme
Feature: Home Screen
  As an App Developer
  I want to see an example feature work on a default alloy app
  So that I can start using TiCalabash quickly

WARN: 
Calabash::Cucumber::Launcher #calabash_no_launch? and support for the NO_LAUNCH
environment variable has been removed from Calabash.  This always returns
true.  Please remove this method call from your hooks.

  Scenario: See Home Screen                          # features/home_screen.feature:6
  App does not exist at path or is not an app bundle.
  
  /Library/Ruby/Gems/2.0.0/gems/run_loop-2.2.0/lib/run_loop/device_agent/app/DeviceAgent-Runner.app
  
  Bundle must:
  
  1. be a directory that exists,
  2. have a .app extension,
  3. contain an Info.plist,
  4. and the app binary (CFBundleExecutable) must exist
   (ArgumentError)
  ./features/ios/support/01_launch.rb:28:in `Before'
    Given I am on the Home Screen                    # features/step_definitions/ticalabash_custom_steps.rb:1
    Then I should see text containing "Hello, World" # calabash-cucumber-0.20.0/features/step_definitions/calabash_steps.rb:356
    And take picture                                 # calabash-cucumber-0.20.0/features/step_definitions/calabash_steps.rb:211
WARN: deprecated '0.20.0' - replaced with attached_to_automator?
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/launcher.rb:251:in `active?'
/Volumes/Data/Development/Appcelerator/Applications/tests/calabash-test/build/iphone/features/ios/support/01_launch.rb:36:in `block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.4.0/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.4.0/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.4.0/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'

Failing Scenarios:
cucumber features/home_screen.feature:6 # Scenario: See Home Screen

1 scenario (1 failed)
3 steps (3 skipped)
0m1.857s
/Volumes/Data/Development/Appcelerator/Applications/tests/calabash-test/build/iphone/features/ios/support/01_launch.rb:45:in `block in <top (required)>': uninitialized constant Calabash::Cucumber::SimulatorHelper (NameError)
```

I'm on macOS Sierra, and using version 6.0.0.GA of Titanium SDK.

Thank you for your work!

**Comment by libosama** [comment]
how to solve it
